### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by fastel** [pylon/penelope#24]
Hi. To make NLP.IntentClassifier example work need to add probability?: true to :svm_classifier options... 

like so: classifier: [{:count_vectorizer, []}, {:svm_classifier, [c: 2.0, probability?: true]}]

in other case it will return :probability_not_trained

**Comment by brentspell** [comment]
Thanks so much for this feedback fastel. This is totally correct, we took a shortcut with the NLP.IntentClassifier module to assume posterior probabilities from the underlying classifier. I will update the docstring for the intent classifier and add an example to the readme. If you have any other feedback please post it!

**Comment by brentspell** [comment]
@fastel I believe your issues have been fixed with the latest PR. Please let me know if you run into any other problems.
